name: Update Edge blocklist

on:
  schedule:
    - cron: '0 6 * * *' # 9:00 MSK
  push:
    branches:
      - main
  #workflow_dispatch:

jobs:
  update_blocklist:
    if: |
        (github.event_name == 'push' || github.event_name == 'pull_request')
        && github.ref == 'refs/heads/main'
        && (startsWith(github.event.head_commit.message, 'txt file') 
            || contains(github.event.head_commit.modified, '.txt'))
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3.4.0
    - name: a
      run: echo "Hello"
    - name: List files
      run: echo ls -la
    - name: Print current directory
      run: echo pwd

    - name: Update Edge blocklist
      run: |
        python -c '
        import urllib.request
        import json
        from subprocess import check_output
        url = "https://edge.microsoft.com/abusiveadblocking/api/v1/blocklist"
        print("hello")
        response = urllib.request.urlopen(url)
        data = json.loads(response.read())
        res = [i["url"] for i in data["sites"]]
        # Get the timestamp of the response
        created_time = data["created_time"]
        # Convert the timestamp to a date string using the date command
        version = check_output(["date", "-d", f"@{created_time}", "+%Y%m%d%H%M"]).decode().strip()
        with open("output/edge_blocklist", "w") as f:
            f.write(
                f"""! Title: MsEdge blocklist
                ! Expires: 1 days
                ! Version: {version}
                ! Homepage: https://github.com/monolit/fuckhosts
                """
                + "\n".join(res)
            )
        '

    - name: Deploy to GitHub Pages
      if: success()
      uses: peaceiris/actions-gh-pages@v3.9.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
        publish_branch: gh-pages

    - name: Commit and push changes
      uses: EndBug/add-and-commit@v9.1.1
      with:
        add: edge_blocklist
        message: Update Edge blocklist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
