name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    if: |
      (github.event_name == 'push' || github.event_name == 'pull_request')
      && github.ref == 'refs/heads/main'
      && (startsWith(github.event.head_commit.message, 'txt file') 
          || contains(github.event.head_commit.modified, '.txt'))
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.11]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Build
      run:  python3 generator.py

    - name: Check GitHub Pages status
      uses: crazy-max/ghaction-github-status@v1
      with:
        pages_threshold: major_outage

    - name: Deploy to GitHub Pages
      if: success()
      uses: peaceiris/actions-gh-pages@v3.9.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
        publish_branch: gh-pages

# https://github.com/marketplace/actions/add-commit
#    - name: Commit
#      uses: EndBug/add-and-commit@v9.1.1
#      if: success()
#      with:
#        add: output
#        message: Commit
